version: '3'

services:
  postgres:
    image: postgres:14.6-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ../schema/init.sql:/docker-entrypoint-initdb.d/init.sql