version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdata:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      - ./influxclidata/temp/influxdb2:/var/lib/influxdb2:rw
    entrypoint: influx setup --host http://192.168.0.200:8086 --org acme --bucket iot-bucket --username benchmark --password ExAmPl3PA55W0rD --force  
    restart: on-failure:10
    depends_on:
      - influxdb
volumes:
  influxdb2: