version: '3'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: timescaledb
    volumes:
      - ./timescaledata:/var/lib/postgresql/data